name: base
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - notebook=5.7.8
  - numpy=1.16.2
  - numpy-base=1.16.2
  - numpydoc=0.8.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - python=3.7.3
